### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by yuangu** [Mu-Y/SynthSing#1]
How to got those data of prev.phn.identity,cur.phn.identity,next phn.identity and pos.-in-phn

**Comment by Mu-Y** [comment]
Hi,

Sorry for the delayed response. The previous repo is a very initial release. Now we release our pre-processed data. Take a look at the README. Also our final report mentioned a bit details for data pre-processing. Feel free to take a look too.

Thanks.

**Comment by Mu-Y** [comment]
close
